version: "3.7"
networks:
  springapimysql-net:
volumes:
  mysql_data:

services:
  mysqldb:
    image: "mysql:8.0"
    container_name: mysqldb
    restart: always
    ports:
      - 3306:3306
    networks:
      - springapimysql-net
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
